global:
  imagePullPolicy: IfNotPresent

catalogue:
  image: nadunimadawala/toy-catalogue
  tag: latest
  replicas: 2

cart:
  image: nadunimadawala/toy-cart
  tag: latest

user:
  image: nadunimadawala/toy-user
  tag: latest

payment:
  image: nadunimadawala/toy-payment
  tag: latest

ratings:
  image: nadunimadawala/toy-ratings
  tag: latest

dispatch:
  image: nadunimadawala/toy-dispatch
  tag: latest

shipping:
  image: nadunimadawala/toy-shipping
  tag: latest

web:
  image: nadunimadawala/toy-web
  tag: latest

mongo:
  image: mongo:6

mysql:
  image: mysql:8
  rootPassword: rootpass

redis:
  image: redis:7

rabbitmq:
  image: rabbitmq:3-management

psp:
  enabled: true

rbac:
  enabled: false

imagePullSecrets:
  - name: dockerhub-secret
  
