apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: toyshop-binding
subjects:
- kind: ServiceAccount
  name: toyshop
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: toy-shop-role
  apiGroup: rbac.authorization.k8s.io
