apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
spec:
  replicas: {{ .Values.cart.replicas }}
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: "{{ .Values.catalogue.image }}:{{ .Values.catalogue.tag }}"
        ports:
        - containerPort: 8080
