version: "3.8"

services:
  dispatch:
    build: .
    container_name: toy-dispatch
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: toy-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
